// <auto-generated />
namespace ResultPlusPlus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class new12356 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new12356));
        
        string IMigrationMetadata.Id
        {
            get { return "202104010643449_new12356"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
